name: SonarQube Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read

jobs:
  sonarqube:
    runs-on: sonar

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=hospital-management-system

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Send success mail
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ✅ SonarQube Security Scan Passed
          body: |
            Hi,

            SonarQube security scan completed successfully.
            No vulnerabilities were found.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}

            ✅ Pipeline Status: SUCCESS
          to: ${{ secrets.SECURITY_MAIL_TO }}
          from: CI Pipeline <${{ secrets.SMTP_USERNAME }}>

      - name: Send failure mail
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ❌ SonarQube Security Scan Failed
          body: |
            Hi,

            SonarQube security scan FAILED.
            Vulnerabilities or Quality Gate conditions were violated.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}

            ❌ Pipeline Status: FAILED

            Please check SonarQube dashboard for details.
          to: ${{ secrets.SECURITY_MAIL_TO }}
          from: CI Pipeline <${{ secrets.SMTP_USERNAME }}>
